// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbAX76Wqrf9sAN4ryWafQqpVkRSbqeAGo',
    appId: '1:185342886878:web:786a6794fb5b9848f5934f',
    messagingSenderId: '185342886878',
    projectId: 'fonemas-kit',
    authDomain: 'fonemas-kit.firebaseapp.com',
    storageBucket: 'fonemas-kit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD85S48-cCy7Gc1kLWdpQ2VO65QS3MW13U',
    appId: '1:185342886878:android:3f047cd718b3a806f5934f',
    messagingSenderId: '185342886878',
    projectId: 'fonemas-kit',
    storageBucket: 'fonemas-kit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYCqatbJtrJYRT4EECd1rMwxk6QQ74nQQ',
    appId: '1:185342886878:ios:27fad85b09d63fb2f5934f',
    messagingSenderId: '185342886878',
    projectId: 'fonemas-kit',
    storageBucket: 'fonemas-kit.firebasestorage.app',
    androidClientId: '185342886878-ckpvarq71q2jupif0ev1uvedf13o25os.apps.googleusercontent.com',
    iosClientId: '185342886878-sedv5jfvaok5phd2dbmrp35vhavh1n8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fonemasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYCqatbJtrJYRT4EECd1rMwxk6QQ74nQQ',
    appId: '1:185342886878:ios:27fad85b09d63fb2f5934f',
    messagingSenderId: '185342886878',
    projectId: 'fonemas-kit',
    storageBucket: 'fonemas-kit.firebasestorage.app',
    androidClientId: '185342886878-ckpvarq71q2jupif0ev1uvedf13o25os.apps.googleusercontent.com',
    iosClientId: '185342886878-sedv5jfvaok5phd2dbmrp35vhavh1n8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fonemasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbAX76Wqrf9sAN4ryWafQqpVkRSbqeAGo',
    appId: '1:185342886878:web:e014652343802db7f5934f',
    messagingSenderId: '185342886878',
    projectId: 'fonemas-kit',
    authDomain: 'fonemas-kit.firebaseapp.com',
    storageBucket: 'fonemas-kit.firebasestorage.app',
  );

}